# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3119635baccd8eaa8b92a8b10788f24"
name = "analytics-audit"
application_url = "https://analytics-audit.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,read_script_tags,read_pixels,read_content"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://analytics-audit.fly.dev/auth/callback",
  "https://analytics-audit.fly.dev/auth/shopify/callback",
  "https://analytics-audit.fly.dev/api/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
